### PR TITLE
catalyst-node: handle vod source urls without hitting load-balancer

### PR DESCRIPTION
**Pull request by emranemran**

### CODE REVIEW

**Review by yondonfu — APPROVED** [review]
LGTM!

Let's also add an issue to track using a shared def for stream prefixes so we don't need to manage stream prefixes here as well as in https://github.com/livepeer/catalyst-api/blob/main/config/stream_names.go#L12

**Comment by yondonfu** [comment]
Looks like the Drone build is failing, but they've been failing for all PRs even before this one...Let's look into that separately.

**Comment by emranemran** [comment]
> Looks like the Drone build is failing, but they've been failing for all PRs even before this one...Let's look into that separately.

File https://github.com/livepeer/catalyst/issues/178

**Comment by emranemran** [comment]
> LGTM!
> 
> Let's also add an issue to track using a shared def for stream prefixes so we don't need to manage stream prefixes here as well as in https://github.com/livepeer/catalyst-api/blob/main/config/stream_names.go#L12

Filed https://github.com/livepeer/catalyst/issues/178

**Comment by emranemran** [comment]
> Looks like the Drone build is failing, but they've been failing for all PRs even before this one...Let's look into that separately.

Yeah this one needs to be looked at - these failures have been consistent and fairly random for several weeks now.

**Pull request merged**
